//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moryx.Demo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Moryx.Demo.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article.
        /// </summary>
        public static string ARTICLE {
            get {
                return ResourceManager.GetString("ARTICLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string CELL_STATE {
            get {
                return ResourceManager.GetString("CELL_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circuit Board.
        /// </summary>
        public static string CIRCUIT_BOARD {
            get {
                return ResourceManager.GetString("CIRCUIT_BOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string COLOR {
            get {
                return ResourceManager.GetString("COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string COMPANY {
            get {
                return ResourceManager.GetString("COMPANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string COMPLETED {
            get {
                return ResourceManager.GetString("COMPLETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Cabinet.
        /// </summary>
        public static string CONTROL_CABINET {
            get {
                return ResourceManager.GetString("CONTROL_CABINET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycles.
        /// </summary>
        public static string CYCLES_SINCE_MAINTENANCE {
            get {
                return ResourceManager.GetString("CYCLES_SINCE_MAINTENANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diameter.
        /// </summary>
        public static string DIAMETER {
            get {
                return ResourceManager.GetString("DIAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string DISABLED {
            get {
                return ResourceManager.GetString("DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DONE.
        /// </summary>
        public static string DONE {
            get {
                return ResourceManager.GetString("DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string FAILED {
            get {
                return ResourceManager.GetString("FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string HEIGHT {
            get {
                return ResourceManager.GetString("HEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Housing.
        /// </summary>
        public static string HOUSING {
            get {
                return ResourceManager.GetString("HOUSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hysteresis.
        /// </summary>
        public static string HYSTERESIS {
            get {
                return ResourceManager.GetString("HYSTERESIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        public static string IDENTIFIER {
            get {
                return ResourceManager.GetString("IDENTIFIER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance Count.
        /// </summary>
        public static string INSTANCE_COUNT {
            get {
                return ResourceManager.GetString("INSTANCE_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Instruction.
        /// </summary>
        public static string MAINTENANCE_INSTRUCTION {
            get {
                return ResourceManager.GetString("MAINTENANCE_INSTRUCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance threshold.
        /// </summary>
        public static string MAINTENANCE_THRESHOLD {
            get {
                return ResourceManager.GetString("MAINTENANCE_THRESHOLD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Mode.
        /// </summary>
        public static string MANUAL_MODE {
            get {
                return ResourceManager.GetString("MANUAL_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Identifier.
        /// </summary>
        public static string MATERIAL_IDENTIFIER {
            get {
                return ResourceManager.GetString("MATERIAL_IDENTIFIER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start maintenance.
        /// </summary>
        public static string METHOD_DO_MAINTENANCE {
            get {
                return ResourceManager.GetString("METHOD_DO_MAINTENANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish notification.
        /// </summary>
        public static string METHOD_PUBLISH_NOTIFICATION {
            get {
                return ResourceManager.GetString("METHOD_PUBLISH_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start a wear down cycle.
        /// </summary>
        public static string METHOD_WEAR_CYCLE {
            get {
                return ResourceManager.GetString("METHOD_WEAR_CYCLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nominal Power.
        /// </summary>
        public static string NOMINAL_POWER {
            get {
                return ResourceManager.GetString("NOMINAL_POWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string NUMBER {
            get {
                return ResourceManager.GetString("NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaged.
        /// </summary>
        public static string PACKAGED {
            get {
                return ResourceManager.GetString("PACKAGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaged parts.
        /// </summary>
        public static string PACKING_COUNT {
            get {
                return ResourceManager.GetString("PACKING_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please follow the maintenance instructions for the packing robot.
        /// </summary>
        public static string PACKING_MAINTENANCE_MESSAGE {
            get {
                return ResourceManager.GetString("PACKING_MAINTENANCE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing Robot requires maintenance.
        /// </summary>
        public static string PACKING_MAINTENANCE_TITLE {
            get {
                return ResourceManager.GetString("PACKING_MAINTENANCE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing Quantity.
        /// </summary>
        public static string PACKING_QUANTITY {
            get {
                return ResourceManager.GetString("PACKING_QUANTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plug Article.
        /// </summary>
        public static string PLUG_PRODUCT_TYPE {
            get {
                return ResourceManager.GetString("PLUG_PRODUCT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POSTPONE.
        /// </summary>
        public static string POSTPONE {
            get {
                return ResourceManager.GetString("POSTPONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printed circuit boards.
        /// </summary>
        public static string PRINTED_CIRCUIT_BOARD {
            get {
                return ResourceManager.GetString("PRINTED_CIRCUIT_BOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservations.
        /// </summary>
        public static string RESERVATIONS {
            get {
                return ResourceManager.GetString("RESERVATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrapped.
        /// </summary>
        public static string SCRAPPED {
            get {
                return ResourceManager.GetString("SCRAPPED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen.
        /// </summary>
        public static string SCREEN {
            get {
                return ResourceManager.GetString("SCREEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip Printing.
        /// </summary>
        public static string SKIP_PRINTING {
            get {
                return ResourceManager.GetString("SKIP_PRINTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please replace the soldering tip..
        /// </summary>
        public static string SOLDERING_MAINTENANCE_MESSAGE {
            get {
                return ResourceManager.GetString("SOLDERING_MAINTENANCE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soldering machine requires maintenance.
        /// </summary>
        public static string SOLDERING_MAINTENANCE_TITLE {
            get {
                return ResourceManager.GetString("SOLDERING_MAINTENANCE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soldering Points.
        /// </summary>
        public static string SOLDERING_POINT {
            get {
                return ResourceManager.GetString("SOLDERING_POINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soldering Temperature.
        /// </summary>
        public static string SOLDERING_TEMPERATURE {
            get {
                return ResourceManager.GetString("SOLDERING_TEMPERATURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success Rate.
        /// </summary>
        public static string SUCCESS_RATE {
            get {
                return ResourceManager.GetString("SUCCESS_RATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string TEST_DESCRIPTOR {
            get {
                return ResourceManager.GetString("TEST_DESCRIPTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Time.
        /// </summary>
        public static string TEST_TIME {
            get {
                return ResourceManager.GetString("TEST_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total cycles.
        /// </summary>
        public static string TOTAL_CYCLES {
            get {
                return ResourceManager.GetString("TOTAL_CYCLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltage.
        /// </summary>
        public static string VOLTAGE {
            get {
                return ResourceManager.GetString("VOLTAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string WEIGHT {
            get {
                return ResourceManager.GetString("WEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string WIDTH {
            get {
                return ResourceManager.GetString("WIDTH", resourceCulture);
            }
        }
    }
}
