name: 'Build and Publish'

on:
  workflow_dispatch:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

env:
  dotnet_sdk_version: '8.0.404'

jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        id: cache-nuget
        with:
          path:  ${{ github.workspace }}/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: 🔧 Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.dotnet_sdk_version }}

      - name: 🔧 Setup nuget
        uses: nuget/setup-nuget@v1

      - name: ♺ Execute nuget restore
        run: nuget restore
        if: steps.cache-nuget.outputs.cache-hit != 'true'

      - name: 🔨 Execute dotnet publish
        run: |
          dotnet publish -c Release -o ./publish
        shell: pwsh
 
      - name: ⬆️ Upload publish artifacts
        uses: actions/upload-artifact@v4
        with:
          name: publish
          path: ./publish/
          retention-days: 1
          if-no-files-found: error
