{
 "title": "MORYX Platform",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Good parts",
   "type": "stat",
   "gridPos": { "h": 10, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"success\") FROM \"processEngine_processes\" WHERE $timeFilter AND \"success\" = true",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "OEE",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processEngine_processes",
     "query": "SELECT count(\"success\") as successCount FROM processEngine_processes WHERE $timeFilter AND success = true",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processEngine_processes",
     "query": "SELECT count(\"cycleTime\") as total FROM processEngine_processes WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(runtime) from (SELECT mean(\"runtimeMs\") as runtime FROM \"processEngine_activities\" WHERE $timeFilter AND \"order\" != '' GROUP BY \"type\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "Select sum(waittime) from (SELECT mean(\"waitTimeMS\") as waittime FROM \"processEngine_activities\" WHERE $timeFilter AND \"order\" != '' GROUP BY \"type\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    { "expression": "($success/$total) * 100", "type": "math" },
    {
     "expression": "($runtime/($runtime + $waittime/8)) ",
     "type": "math"
    },
    { "expression": "performance", "reducer": "last", "type": "reduce" },
    { "expression": "percentage", "reducer": "last", "type": "reduce" },
    {
     "expression": "$percentageValue * $performanceValue * 100",
     "type": "math"
    }
   ]
  },
  {
   "title": "CycleTime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processEngine_processes",
     "query": "SELECT mean(\"cycleTime\")  FROM processEngine_processes WHERE $timeFilter GROUP BY time(5m) fill(0)",
     "select": [
      [
       { "params": [ "cycleTime" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "parts/minute" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processEngine_processes",
     "query": "SELECT count(\"success\") AS success_count, count(\"id\") AS id_count FROM \"processEngine_processes\" WHERE $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "id" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cycle time composition",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" }
     ],
     "measurement": "processEngine_activities",
     "query": "SELECT mean(\"runtimeMs\") as runtime, mean(\"waittimeMS\") as waittime FROM \"processEngine_activities\" WHERE $timeFilter AND \"order\" != '' GROUP BY \"type\"",
     "select": [
      [
       { "params": [ "runtimeMs" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "waittimeMS" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Throughput by cell",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "resource" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "processEngine_activities",
     "query": "SELECT mean(\"processes\") FROM (SELECT count(\"process\") as \"processes\" FROM \"processEngine_activities\" WHERE $timeFilter GROUP BY time(1m), \"resource\") GROUP BY \"resource\"",
     "select": [
      [
       { "params": [ "process" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 2, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"success\") as successCount FROM processEngine_processes WHERE $timeFilter AND success = true",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"cycleTime\") as total FROM processEngine_processes WHERE $timeFilter AND \"order\" != ''",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    { "expression": "$success/$total * 100", "type": "math" }
   ]
  },
  {
   "title": "Scrap",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"success\") FROM processEngine_processes WHERE $timeFilter AND \"success\" = false AND \"order\" != ''\n\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Failed activities by cell",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 11, "x": 2, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "resource" ], "type": "tag" }
     ],
     "measurement": "processEngine_activities",
     "query": "SELECT count(\"id\") FROM \"processEngine_activities\" WHERE $timeFilter AND \"success\" = false GROUP BY \"resource\"",
     "select": [
      [
       { "params": [ "id" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Soldering temperature by cell",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "resource" ], "type": "tag" }
     ],
     "measurement": "processEngine_activities",
     "query": "SELECT \"solderingTemp\" FROM \"processEngine_activities\" WHERE $timeFilter GROUP BY \"resource\"",
     "select": [
      [
       { "params": [ "id" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Soldering Power ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Soldering Machine-1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cell_report",
     "query": "SELECT mean(\"current_power\") FROM \"cell_report\" WHERE (\"source\" = 'Soldering Machine-1') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "current_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "Auto-Solder-1" }
     ]
    },
    {
     "alias": "Soldering Machine-2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cell_report",
     "query": "SELECT mean(\"current_power\") FROM \"cell_report\" WHERE (\"source\" = 'Soldering Machine-2') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "current_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "source", "operator": "=", "value": "Auto-Solder-2" }
     ]
    }
   ]
  },
  {
   "title": "CO2 per Part",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" }
     ],
     "measurement": "processEngine_activities",
     "query": "SELECT (mean(\"energy\") * 366) as \"carbon\" FROM (SELECT (\"energy\" / 1000 * \"runtimeMs\" / 3600000) as \"energy\" FROM \"processEngine_activities\" WHERE $timeFilter AND \"order\" != '' GROUP BY \"type\") GROUP BY \"type\"",
     "select": [
      [
       { "params": [ "runtimeMs" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "waittimeMS" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Energy Utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT sum(\"current_power\") as Total FROM \"cell_report\" WHERE $timeFilter "
    },
    {
     "query": "SELECT sum(\"energy\") as Productive FROM (SELECT (energy*runtimeMs)/ 3600000 as energy FROM \"processEngine_activities\" WHERE $timeFilter AND \"order\" != '') "
    },
    { "type": "reduce", "expression": "total", "reducer": "last" },
    { "type": "reduce", "expression": "used", "reducer": "last" },
    { "expression": "$usedValue / $totalValue * 100", "type": "math" }
   ]
  }
 ]
}